# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssl-vpn
  template:
    metadata:
      labels:
        app: ssl-vpn
    spec:
      containers:
      - name: ssl-vpn
        image: simondelord/ssl:latest
        securityContext:
          privileged: true
        volumeMounts:
        - mountPath: /run
          name: run-volume
        - mountPath: /run/lock
          name: lock-volume
        - mountPath: /tmp
          name: tmp-volume
        - mountPath: /lib/modules
          name: modules-volume
        ports:
        - containerPort: 443
      volumes:
      - name: run-volume
        hostPath:
          path: /run
      - name: lock-volume
        hostPath:
          path: /run/lock
      - name: tmp-volume
        hostPath:
          path: /tmp
      - name: modules-volume
        hostPath:
          path: /lib/modules
