# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssl-vpn
  template:
    metadata:
      labels:
        app: ssl-vpn
    spec:
      containers:
      - name: ssl-vpn
        image: simondelord/ssl:latest
        volumeMounts:
        - mountPath: /run
          name: run-volume
        - mountPath: /run/lock
          name: lock-volume
        - mountPath: /tmp
          name: tmp-volume
        ports:
        - containerPort: 443
      volumes:
      - name: run-volume
        emptyDir: {}
      - name: lock-volume
        emptyDir: {}
      - name: tmp-volume
        emptyDir: {}
