# deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ssl-vpn
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ssl-vpn
  template:
    metadata:
      labels:
        app: ssl-vpn
    spec:
      containers:
      - name: ssl-vpn
        image: simondelord/ssl:latest
        ports:
        - containerPort: 443
